# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Server CI

on: push

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    env:
      MONGO_URL_TEST: 'mongodb://localhost:27017/branddb_test'
      PORT: 5000
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
      CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['4.4']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-replica-set: test-rs
        mongodb-port: 27017
    - name: Install dependencies
      working-directory: backend/
      run: npm install
    - name: Run build
      working-directory: backend/
      run: npm run build --if-present
    - name: Run test
      working-directory: backend/
      run: npm run test
      env:
        CI: true
    - name: Run coverage
      working-directory: backend/
      run: npm run coverage
    - name: Coveralls
      working-directory: backend/
      run: npm run coveralls
